language: node_js
node_js:
  - 6.9.1
  - 10
before_script:
  - npm install -g gulp
# Send coverage data to Coveralls
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
